
project_id = "odzaacarlkmxqrpmggwe"

[functions."learn-ai"]
verify_jwt = true

[functions."mondai-ai"]
verify_jwt = false
cors = ["*"]
headers = { "Access-Control-Allow-Origin" = "*", "Access-Control-Allow-Headers" = "*" }

